# Generated by Django 4.2.26 on 2026-06-09 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_backfill_user_profiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='due_time',
        ),
    ]
