# Generated by Django 4.2.26 on 2026-06-10 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_remove_room_due_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='guest_items',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
