# Generated by Django 4.2.26 on 2026-06-16 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operations', '0007_room_attention_resolved'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomAssignmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_to_name', models.CharField(blank=True, default='', max_length=150)),
                ('assigned_to_initials', models.CharField(blank=True, default='', max_length=10)),
                ('assigned_to_shift', models.CharField(blank=True, default='', max_length=50)),
                ('assigned_at', models.DateTimeField()),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('completed', 'Completed')], default='assigned', max_length=20)),
                ('checklist', models.JSONField(blank=True, default=list)),
                ('guest_items', models.JSONField(blank=True, default=list)),
                ('housekeeping_remark', models.TextField(blank=True, default='')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_assignment_logs', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_logs', to='operations.room')),
            ],
            options={
                'ordering': ['-assigned_at', '-id'],
            },
        ),
    ]
